### ISSUE TITLE
GBK encoding error

### ISSUE THREAD

**Issue by SWJDADA** [namtuanly/MTL-TabNet#10]
I would like to know how to solve the GBK encoding problem. Thank you for your reply.
The error is as follows: File "Traceback (most recent call last):
File "C:/Programming/phytorch_table-rec/MTL TabNet main/table-recognition/demo/demo. py", line 357, in<module>
Tablemaster_ Inference=Structure_ Recognition (args. tablemaster_config, args. tablemaster_checkpoint)
File "C:  Programming  pytorch_table-rec  MTL TabNet main  table-recognition  table_inference. py", line 62, in__ Init__
Super()__ Init__ (config_file, checkpoint file)
File "C:  Programming  pytorch_table-rec  MTL TabNet main  table-recognition  table_inference. py", line 38, in__ Init__
Self. model=build_ Model (config_file, checkpoint file)
File "C:  Programming  pytorch_table-rec  MTL TabNet main  table-recognition  table_inference. py", line 25, in build_ Model
Model=init_ Detector (config_file, checkpoint=checkpoint file, device=device)
File "c:  approgramming  pytorch_tablerec  mtl tablet main  mmdetection-2.11.0  mmdet  apis  conference. py", line 34, in init_ Detector
Config=mmcv Config. fromfile (config)
File "C:  Programming  software  Anaconda3  envs  mtl  lib  site packages  mmcv  utils  config. py", line 331, in from file
Cfg_ Dict, cfg_ Text=Config_ File2dict (filename,
File "C:  Programming  software  Anaconda3  envs  mtl  lib  site packages  mmcv  utils  config. py", line 206, in_ File2dict
Mod=import_ Module (temp_module_name)
File "C:  Programming  software  Anaconda3  envs  mtl  lib  importlib  __init__. py", line 127, in import_ Module
Return_ Bootstrap_ Gcd_ Import (name [level:], package, level)
File "<frozen importlib. _bootstrap>", line 1014, in_ Gcd_ Import
File "<frozen importlib. _bootstrap>", line 991, in_ Find_ And_ Load
File "<frozen importlib. _bootstrap>", line 975, in_ Find_ And_ Load_ Unlocked
File "<frozen importlib. _bootstrap>", line 671, in_ Load_ Unlocked
File "<frozen importlib. _bootstrap_external>", line 843, in exec_ Module
File "<frozen importlib. _bootstrap>", line 219, in_ Call_ With_ Frames_ Removed
File "C:  Users  SWJDADA  AppData  Local  Temp  tmpw1sos64h  tmplf3mr0ss. py", line 11, in<module>
Unicode DecodeError: 'gbk' code can't decode byte 0xa4 in position 77: illegal multibyte sequence
Process finished with exit code 1
C: Users  AA  AppData  Local  Temp  tmpw1sos64h  tmplf3mr0ss. py ", line 11, in<module>
Unicode DecodeError: 'gbk' code can't decode byte 0xa4 in position 77: illegal multibyte sequence

**Comment by jianyu-zheng** [comment]
Hello, have you solved the problem? I also encountered the same problem.

**Comment by SWJDADA** [comment]
> Hello, have you solved the problem? I also encountered the same problem.

This problem has not been resolved yet. Do you have a solution？

**Comment by yayaicode** [comment]
Hello, have you solved the problem so far? I also encountered the same problem and I don't have any idea.
