### ISSUE TITLE
Installing MMCV

### ISSUE THREAD

**Issue by kokul93** [namtuanly/MTL-TabNet#13]
pip install mmcv-full==1.3.4 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
 above command not working

Looking in links: https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html

Collecting mmcv-full==1.3.4
  Using cached mmcv-full-1.3.4.tar.gz (295 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mbtious8/mmcv-full_0a94a8ffea9c419295da4b3397d301b3/setup.py", line 315, in <module>
          ext_modules=get_extensions(),
        File "/tmp/pip-install-mbtious8/mmcv-full_0a94a8ffea9c419295da4b3397d301b3/setup.py", line 235, in get_extensions
          ext_ops = extension(
        File "/home
/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 868, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 976, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1984, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by kokul93** [comment]
Traceback (most recent call last):
  File "./table_recognition/demo/demo.py", line 5, in <module>
    from mmcv.image import imread
    
   how to resolve this?

**Comment by kokul93** [comment]
Solved using older versions
