### ISSUE TITLE
Something wrong about training

### ISSUE THREAD

**Issue by wu-yz** [namtuanly/MTL-TabNet#6]
When running: sh ./table_recognition/expr/table_recognition_dist_train.sh
AssertionError: OCRFinTabDataset: TableHardDiskLoader: /datasets/mmocr_fintabnet_recognition_0726_train/StructureLabelAddEmptyBbox_train/ is not exist
How can I deal with this problem?

**Comment by wu-yz** [comment]
Is there a trained model？I want to run a demo.

**Comment by namtuanly** [comment]
Yes, we have released the pre-trained models of both FinTabNet and PubtabNet.
Please check the pre-trained models and how to run the demo in README.md.

**Comment by namtuanly** [comment]
> 
Did you prepare the training data for FinTabNet?
You need to run "data_preprocess_fintabnet.py" to prepare the training data for FinTabNet.

**Comment by namtuanly** [comment]
> When running: sh ./table_recognition/expr/table_recognition_dist_train.sh AssertionError: OCRFinTabDataset: TableHardDiskLoader: /datasets/mmocr_fintabnet_recognition_0726_train/StructureLabelAddEmptyBbox_train/ is not exist How can I deal with this problem?

Did you prepare the training data for FinTabNet?
You need to run "data_preprocess_fintabnet.py" to prepare the training data for FinTabNet.

**Comment by namtuanly** [comment]
> Is there a trained model？I want to run a demo.

Yes, we have released the pre-trained models of both FinTabNet and PubtabNet.
Please check the pre-trained models and how to run the demo in README.md.

**Comment by wu-yz** [comment]
> > When running: sh ./table_recognition/expr/table_recognition_dist_train.sh AssertionError: OCRFinTabDataset: TableHardDiskLoader: /datasets/mmocr_fintabnet_recognition_0726_train/StructureLabelAddEmptyBbox_train/ is not exist How can I deal with this problem?
> 
> Did you prepare the training data for FinTabNet? You need to run "data_preprocess_fintabnet.py" to prepare the training data for FinTabNet.

Yes,I did.But the mistake still appeared.I'll try it again.

**Comment by wu-yz** [comment]
> > Is there a trained model？I want to run a demo.
> 
> Yes, we have released the pre-trained models of both FinTabNet and PubtabNet. Please check the pre-trained models and how to run the demo in README.md.

Thank you very much for replying!

**Comment by namtuanly** [comment]
> > > When running: sh ./table_recognition/expr/table_recognition_dist_train.sh AssertionError: OCRFinTabDataset: TableHardDiskLoader: /datasets/mmocr_fintabnet_recognition_0726_train/StructureLabelAddEmptyBbox_train/ is not exist How can I deal with this problem?
> > 
> > 
> > Did you prepare the training data for FinTabNet? You need to run "data_preprocess_fintabnet.py" to prepare the training data for FinTabNet.
> 
> Yes,I did.But the mistake still appeared.I'll try it again.

Can you show the whole error message, then I will try to check the reason.

**Comment by wu-yz** [comment]
> > > > When running: sh ./table_recognition/expr/table_recognition_dist_train.sh AssertionError: OCRFinTabDataset: TableHardDiskLoader: /datasets/mmocr_fintabnet_recognition_0726_train/StructureLabelAddEmptyBbox_train/ is not exist How can I deal with this problem?
> > > 
> > > 
> > > Did you prepare the training data for FinTabNet? You need to run "data_preprocess_fintabnet.py" to prepare the training data for FinTabNet.
> > 
> > 
> > Yes,I did.But the mistake still appeared.I'll try it again.
> 
> Can you show the whole error message, then I will try to check the reason.

After running "data_preprocess_fintabnet.py",I find the several folders were empty.Is there anything wrong with fintabnet datasets?

**Comment by namtuanly** [comment]
> > > > > When running: sh ./table_recognition/expr/table_recognition_dist_train.sh AssertionError: OCRFinTabDataset: TableHardDiskLoader: /datasets/mmocr_fintabnet_recognition_0726_train/StructureLabelAddEmptyBbox_train/ is not exist How can I deal with this problem?
> > > > 
> > > > 
> > > > Did you prepare the training data for FinTabNet? You need to run "data_preprocess_fintabnet.py" to prepare the training data for FinTabNet.
> > > 
> > > 
> > > Yes,I did.But the mistake still appeared.I'll try it again.
> > 
> > 
> > Can you show the whole error message, then I will try to check the reason.
> 
> After running "data_preprocess_fintabnet.py",I find the several folders were empty.Is there anything wrong with fintabnet datasets?

I think you have some problems when preparing the jsonl file of FinTabNet.
This jsonl file is the same as the one of PubTabNet.
I will publicize the jsonl as well as the table images of FinTabNet and let you know soon.

**Comment by wu-yz** [comment]
> > > > > > When running: sh ./table_recognition/expr/table_recognition_dist_train.sh AssertionError: OCRFinTabDataset: TableHardDiskLoader: /datasets/mmocr_fintabnet_recognition_0726_train/StructureLabelAddEmptyBbox_train/ is not exist How can I deal with this problem?
> > > > > 
> > > > > 
> > > > > Did you prepare the training data for FinTabNet? You need to run "data_preprocess_fintabnet.py" to prepare the training data for FinTabNet.
> > > > 
> > > > 
> > > > Yes,I did.But the mistake still appeared.I'll try it again.
> > > 
> > > 
> > > Can you show the whole error message, then I will try to check the reason.
> > 
> > 
> > After running "data_preprocess_fintabnet.py",I find the several folders were empty.Is there anything wrong with fintabnet datasets?
> 
> I think you have some problems when preparing the jsonl file of FinTabNet. This jsonl file is the same as the one of PubTabNet. I will publicize the jsonl as well as the table images of FinTabNet and let you know soon.

Thank you so much!

**Comment by namtuanly** [comment]
> > > > > > When running: sh ./table_recognition/expr/table_recognition_dist_train.sh AssertionError: OCRFinTabDataset: TableHardDiskLoader: /datasets/mmocr_fintabnet_recognition_0726_train/StructureLabelAddEmptyBbox_train/ is not exist How can I deal with this problem?
> > > > > 
> > > > > 
> > > > > Did you prepare the training data for FinTabNet? You need to run "data_preprocess_fintabnet.py" to prepare the training data for FinTabNet.
> > > > 
> > > > 
> > > > Yes,I did.But the mistake still appeared.I'll try it again.
> > > 
> > > 
> > > Can you show the whole error message, then I will try to check the reason.
> > 
> > 
> > After running "data_preprocess_fintabnet.py",I find the several folders were empty.Is there anything wrong with fintabnet datasets?
> 
> I think you have some problems when preparing the jsonl file of FinTabNet. This jsonl file is the same as the one of PubTabNet. I will publicize the jsonl as well as the table images of FinTabNet and let you know soon.

I upload the Python script [extract_table_images_FinTabNet.py](https://github.com/namtuanly/MTL-TabNet/blob/main/tools/data/fintabnet/extract_table_images_FinTabNet.py) for extracting table images and making the annotation file (like PubTabNet) from FInTabNet dataset. After that, you can run "data_preprocess_fintabnet.py" to prepare the training dataset for FinTabNet.

**Comment by wu-yz** [comment]
> 

OK，I'll give another try.It is appreciated for answering my question in your busy time.

**Comment by wu-yz** [comment]
> > > > > > > When running: sh ./table_recognition/expr/table_recognition_dist_train.sh AssertionError: OCRFinTabDataset: TableHardDiskLoader: /datasets/mmocr_fintabnet_recognition_0726_train/StructureLabelAddEmptyBbox_train/ is not exist How can I deal with this problem?
> > > > > > 
> > > > > > 
> > > > > > Did you prepare the training data for FinTabNet? You need to run "data_preprocess_fintabnet.py" to prepare the training data for FinTabNet.
> > > > > 
> > > > > 
> > > > > Yes,I did.But the mistake still appeared.I'll try it again.
> > > > 
> > > > 
> > > > Can you show the whole error message, then I will try to check the reason.
> > > 
> > > 
> > > After running "data_preprocess_fintabnet.py",I find the several folders were empty.Is there anything wrong with fintabnet datasets?
> > 
> > 
> > I think you have some problems when preparing the jsonl file of FinTabNet. This jsonl file is the same as the one of PubTabNet. I will publicize the jsonl as well as the table images of FinTabNet and let you know soon.
> 
> I upload the Python script [extract_table_images_FinTabNet.py](https://github.com/namtuanly/MTL-TabNet/blob/main/tools/data/fintabnet/extract_table_images_FinTabNet.py) for extracting table images and making the annotation file (like PubTabNet) from FInTabNet dataset. After that, you can run "data_preprocess_fintabnet.py" to prepare the training dataset for FinTabNet.

OK，I'll give another try.It is appreciated for answering my question in your busy time.

**Comment by vkrtsind** [comment]
> > > Is there a trained model？I want to run a demo.
> > 
> > 
> > Yes, we have released the pre-trained models of both FinTabNet and PubtabNet. Please check the pre-trained models and how to run the demo in README.md.
> 
> Thank you very much for replying!

**Comment by vkrtsind** [comment]
While running on CPU Machine - python demo.py 
Facing ERROR - 

Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    from mmdet.apis import init_detector
  File "/home/n14688/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "/home/n14688/mmdetection/mmdet/apis/det_inferencer.py", line 22, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "/home/n14688/mmdetection/mmdet/evaluation/__init__.py", line 4, in <module>
    from .metrics import *  # noqa: F401,F403
  File "/home/n14688/mmdetection/mmdet/evaluation/metrics/__init__.py", line 5, in <module>
    from .coco_metric import CocoMetric
  File "/home/n14688/mmdetection/mmdet/evaluation/metrics/coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval, COCOevalMP
  File "/home/n14688/mmdetection/mmdet/datasets/__init__.py", line 31, in <module>
    from .utils import get_loading_pipeline
  File "/home/n14688/mmdetection/mmdet/datasets/utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "/home/n14688/mmdetection/mmdet/datasets/transforms/__init__.py", line 6, in <module>
    from .formatting import (ImageToTensor, PackDetInputs, PackReIDInputs,
  File "/home/n14688/mmdetection/mmdet/datasets/transforms/formatting.py", line 11, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "/home/n14688/mmdetection/mmdet/structures/bbox/__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "/home/n14688/mmdetection/mmdet/structures/bbox/base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "/home/n14688/mmdetection/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "/home/n14688/mmdetection/mmdet/structures/mask/structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/home/n14688/anaconda3/envs/MTL/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/n14688/anaconda3/envs/MTL/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/n14688/anaconda3/envs/MTL/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/n14688/anaconda3/envs/MTL/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/n14688/anaconda3/envs/MTL/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6narrowElll
(MTL) n14688@n14688:~/MTL-TabNet/table_r

**Comment by vkrtsind** [comment]
Can we demo.py on CPU  machine ?
